### ISSUE TITLE
Atum REST Service v2

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/atum-service#140]
## Background
The current REST API of the server is not complex nor very REST-full. And very rudimentary.

## Goal
Create proper REST-full API and implement at least its key endpoints.

```[tasklist]
### Tasks
- [ ] https://github.com/AbsaOSS/atum-service/issues/141
- [ ] https://github.com/AbsaOSS/atum-service/issues/145
- [ ] https://github.com/AbsaOSS/atum-service/issues/144
- [ ] https://github.com/AbsaOSS/atum-service/issues/176
- [ ] --- _Partitioning_
- [ ] #268
- [ ] #226
- [ ] #224
- [ ] https://github.com/AbsaOSS/atum-service/issues/273
- [ ] #227
- [ ] #221
- [ ] #229
- [ ] #230
- [ ] #231
- [ ] #232
- [ ] #234
- [ ] --- _Flow_
- [ ] #233
- [ ] #235
- [ ] --- _partitionings_ (eventually)
- [ ] https://github.com/AbsaOSS/atum-service/issues/305
- [ ] GET /partitionings/{partId}/flows vraci sekvenci flows
- [ ] --- _checkpoints_ (eventually)
- [ ] GET /checkpoints?name=, and what not other filters
- [ ] GET /checkpoints/{chekcpointUUId}
```
