### ISSUE TITLE
Make it possible to read all checkpoints of a partitioning

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/atum-service#172]
## Background
Atum is to provide read abilities too, not just write

## Goal
We need to be able to read saved checkpoint data of a given partitioning.

```[tasklist]
### Tasks
- [ ] #177
- [ ] https://github.com/AbsaOSS/atum-service/issues/189
- [ ] https://github.com/AbsaOSS/atum-service/issues/190
- [x] ~Add the ability to `AtumAgent`~ (maybe, depending on #179 )
```

**Comment by lsulak** [comment]
Done! Not part of Agent yet as we talked that we'll only add it if / after a while, if it will be convenient for our users / usage of it.
