### ISSUE TITLE
Read data of checkpoint of certain name of a given flow

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/atum-service#180]
## Background
Atum is to provide read abilities too, not just write

## Goal
We need to read all the measurements across a checkpoint of certain name within a flow.

```[tasklist]
### Tasks
- [ ] #177 
- [ ] #178 
- [ ] https://github.com/AbsaOSS/atum-service/issues/187
- [ ] https://github.com/AbsaOSS/atum-service/issues/188
- [x] ~Add the ability to `AtumAgent`~ (maybe, depending on #179 )
```

**Comment by lsulak** [comment]
Done! Not part of Agent yet as we talked that we'll only add it if / after a while, if it will be convenient for our users / usage of it.
