### ISSUE TITLE
Create a module, that will read information stored on the server

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/atum-service#243]
## Background
With the increased interest in _Atum_, and particularly the consumption of the data stored, and with the requirements of securing the server APIs, it will be beneficial to solve the information access in one library, This will simplify the usage and avoid the need of re-implementation in each application.

## Goal
A library which will make it easy to plug in into an application and read the information stored on Atum server.

```[tasklist]
### Tasks
- [ ] #244
- [ ] https://github.com/AbsaOSS/atum-service/issues/245
- [ ] https://github.com/AbsaOSS/atum-service/issues/246
- [ ] https://github.com/AbsaOSS/atum-service/issues/247
- [ ] https://github.com/AbsaOSS/atum-service/issues/254
```
