### ISSUE TITLE
Release and deploy of Atum v0.3.0 - development

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/atum-service#257]
## Background
Long time again since Atum release and even longer since deploy.

## Goal
Release and deploy of version 0.3.0
Secondary goal is to streamline the deploy process to allow more frequent releases and their smooth deploy.

```[tasklist]
### Tasks
- [ ] #260
- [ ] #262
- [ ] #263
- [ ] https://github.com/AbsaOSS/atum-service/issues/278
- [ ] https://github.com/AbsaOSS/atum-service/issues/280
- [ ] #284
- [ ] https://github.com/AbsaOSS/atum-service/issues/285
```
