### ISSUE TITLE
Data exchange between agent and server

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/atum-service#36]
## Background
Agent and server need to exchange data. Particularly agent needs to send checkpoint control measurements and additional data to the server. And occasionally pull the _Segmentation_ definition.

## Goal
Establish a data exchange pipeline between Agent and Server.

```[tasklist]
### Tasks
- [x] https://github.com/AbsaOSS/atum-service/issues/37
- [ ] #10
- [ ] #7
- [ ] https://github.com/AbsaOSS/atum-service/issues/38
- [ ] https://github.com/AbsaOSS/atum-service/issues/52
- [ ] https://github.com/AbsaOSS/atum-service/issues/53
- [ ] https://github.com/AbsaOSS/atum-service/issues/54
```
