### ISSUE TITLE
Support partitioning in database

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/atum-service#67]
## Background
`AtumPartitioning` is a `LinkedMap[String, String]`, the order of the keys matters.

## Goal
We need to add database support to effectively store such data and convert them between Scala and Postgres.

```[tasklist]
### Tasks
- [ ] https://github.com/AbsaOSS/atum-service/issues/68
- [ ] https://github.com/AbsaOSS/atum-service/issues/69
- [ ] https://github.com/AbsaOSS/atum-service/issues/70
- [ ] https://github.com/AbsaOSS/atum-service/issues/71
```
